export enum ROOM_TYPE {
    GOAT = "염소",
    CAR = "차"
}

export enum GAME_TYPE {
    READY,
    RUNNING,
    FINISH,
}

export const LS_RESULTS_CHANGED: string = "LS_RESULTS_CHANGED"
export const LS_RESULTS_NOT_CHANGED: string = "LS_RESULTS_NOT_CHANGED"

export enum STORAGE_RESULT {
    LS_RESULTS_CHANGED = "LS_RESULTS_CHANGED",
    LS_RESULTS_NOT_CHANGED = "LS_RESULTS_NOT_CHANGED",
    RESULT_FAIL = "0",
    RESULT_SUCCESS = "1",
}